### PR TITLE
#25 - make input.value get set when option is clicked

### PR DESCRIPTION
**Pull request by master-elodin**
When an option is clicked, set `input.value` and clear results

### CODE REVIEW

**Comment by ritz078** [comment]
I will see this on weekends. :)

**Comment by ritz078** [comment]
the tests seem to be failing. Have you run `yarn test`?

**Comment by master-elodin** [comment]
Strange! They're passing for me. Which ones are failing for you?

```bash
timvandoren@mycomputer react-fuzzy-search (fix-click)$ yarn test
... [linter info] ...

> react-fuzzy@0.5.2 testonly /Users/timvandoren/Documents/dev/git/react-fuzzy-search
> mocha --require .scripts/mocha_runner src/**/tests/**/*.js

Warning: ReactTestUtils has been moved to react-dom/test-utils. Update references to remove this warning.

  <FuzzySearch />
Warning: `value` prop on `input` should not be null. Consider using the empty string to clear the component or `undefined` for uncontrolled components.
    in input (created by FuzzySearch)
    in div (created by FuzzySearch)
    in div (created by FuzzySearch)
    in FuzzySearch (created by WrapperComponent)
    in WrapperComponent
    ✓ should set correct placeholder text
    ✓ should show results on typing
    ✓ should set results as ids if passed in options
Warning: FuzzySearch is changing an uncontrolled input of type text to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://fb.me/react-controlled-components
    ✓ should call onChange on selection of result if enter clicked
    ✓ should call onSelect on selection of result if mouse clicked
    ✓ should overwrite previous props with options passed in
    ✓ should set input value even if no title on selectedValue (if ID set)


  7 passing (124ms)

✨  Done in 218.28s.
timvandoren@mycomputer react-fuzzy-search (fix-click)$
```

**Comment by PatrickDesign** [comment]
Closed by #52.

**Pull request closed without merging**
