### PR TITLE
[FEATURE] Add `shouldShowDropdownAtStart` prop

### PR DESCRIPTION
**Pull request by PatrickDesign**
## Summary

Fix Storybook dev environment by reverting package updates in #48

Add 1 new prop:

attribute|default|description
---------|-------|-----------
shouldShowDropdownAtStart|false|Allow the searchbox to act as a `filter` dropdown with initial values. Yields all results when the search value is blank.

Video: [🎥](https://snap.anedot.com/patrick.wees/screencast_2020-12-03_13-54-03.mp4)

### CODE REVIEW

**Comment by ritz078** [comment]
The prop name is a bit confusing. Can it be something like `isDropdown` or `showAllOptions` ?

**Comment by PatrickDesign** [comment]
> The prop name is a bit confusing. Can it be something like `isDropdown` or `showAllOptions` ?

I was going to name it `isDropdown`, but then I realized that the default behavior could almost be considered `dropdown` already.. ha. I think `filter` makes sense because it implies that you are starting with all options, instead of "searching" from nothing.

**Comment by ritz078** [comment]
I think we are leaving too much to the user's wonder. `showDropdownAtStart` should make it clear ?

**Review by ritz078 — APPROVED** [review]

**Comment by ritz078** [comment]
@PatrickDesign Feel free to merge the PR when you are ready.

**Comment by PatrickDesign** [comment]
@ritz078  this could probably use another quick lookover as I adjusted the `onBlur` method to act more like a dropdown.  Will merge in a few days either way 🙇

**Pull request merged**
